packages:
  - packages/**
  - apps/**

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
  types:
    typescript: ^5.8.3
    "@types/node": ^20
  build:
    rimraf: ^6.0.1
    tsup: ^8.4.0
  cli:
    inquirer: ^12.5.2
    turbo: ^2.5.0
  lint:
    "@biomejs/biome": ^2.0.6
  dev:
    "@ladle/react": ^5.0.2
  animation:
    gsap: ^3.12.7
    "@gsap/react": ^2.1.2
  utils:
    "es-toolkit": ^1.36.0
    rxjs: ^7.8.2
    usehooks-ts: ^3.1.1
    zod: ^3.25.76
    dotenv: ^16.5.0
    ky: 1.7.5
  ai:
    "@agentic/ai-sdk": ^7.6.5
    "@agentic/core": ^7.6.5
    ai: ^5
    "@ai-sdk/openai": ^2
    "@ai-sdk/react": ^2
    "@ai-sdk/provider": ^2
    "@ai-sdk/provider-utils": ^3
  test:
    "vitest": ^3.2.4
